version: "3.9"
services:
  redis:
    image: redis
    restart: on-failure
  database:
    image: postgres
    restart: on-failure
    volumes:
      - ./database:/var/lib/postgresql
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_PORT=${DB_PORT}
  helios:
    build: .
    restart: on-failure
    ports:
      - "8000:8000"
    links:
      - "redis:redis"
      - "database:database"
    env_file:
      - .env
    environment:
      - OPERATION_MODE=${WEBSERVER_MODE}
    depends_on:
      - database
    volumes: 
      - ./:/home/app/
  celery:
    build: .
    volumes:
      - ./:/home/app
    environment:
      - OPERATION_MODE="CELERY"
    env_file:
      - .env
    depends_on:
      - database
      - redis
      - helios
    
